name: 'Build and Test Eclipse Installation Manager'

on:
  workflow_dispatch:
  push:
    branches:
     - 'main'
  pull_request:
    branches:
     - 'main'

jobs:
  start:
    runs-on: ubuntu-latest
    steps:
     - uses: actions/checkout@v2
       with:
        fetch-depth: 0
     - 
      name: Build application, run tests and create coverage reports
      id: script
      run: |
        /rm -rf ${{ github.workspace }}/cnf/release
        /bin/bash ${{ github.workspace }}/buildAndTest.sh
     -
      name: Create release and upload artifacts to release
      env:
        GH_TOKEN: ${{ github.token }}
      run: |
        export github_workspace=${{ github.workspace }}
        /bin/bash ${{ github.workspace }}/createReleaseAndArtifacts.sh
